version: '3.9'
services:
  xenon-mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
      - ./orchestration/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_ROOT_NAME}
      MONGO_USERNAME: ${MONGODB_USER}
      MONGO_PASSWORD: ${MONGODB_PASS}
      MONGO_DATABASE: ${MONGODB_NAME}
    networks:
      xenon-network:

  xenon-redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      xenon-network:

  xenon-bot:
    container_name: bot
    image: haiyn/xenon-bot:${RELEASE_VERSION}
    env_file:
      - .env
    restart: on-failure:3
    ports:
      -  8089:8089
    networks:
      xenon-network:

networks:
  xenon-network:
    driver: bridge

volumes:
  mongodb: